* Like to solve the ODD or EVEN Code-Kata
REPORT zdp_odd_or_even.

CLASS ltc_odd_or_even DEFINITION FOR TESTING RISK LEVEL HARMLESS DURATION SHORT.
  PUBLIC SECTION.
    METHODS:
      x FOR TESTING.
ENDCLASS.

CLASS ltc_odd_or_even IMPLEMENTATION.
  METHOD x.
  ENDMETHOD.
ENDCLASS.
